export const TRANSLATE_TEXT = 'Перевод слова:'
export const TRANSLATE_INPUT_TEXT = 'Перевод'
export const RESULT_TITLE = 'Результат'
export const COMPLETE_TEXT = 'Верно: '
export const ERROR_TEXT = 'Не верно:'